name: "CI"
on: [push]

jobs:
  test:
    strategy:
      matrix:
        container: ["node:current", "node:lts"]

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
    # Prepare
    - uses: actions/checkout@v2
    - name: "Show version"
      run: |
        node --version
        npm --version
    - run: npm ci
    # Run
    - run: npm run lint
    - run: npm run build
    - run: npm run test
