name: "CI"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: "node:current"
    steps:
    # Prepare
    - uses: actions/checkout@v2
    - run: |
        npm i -g npm
        npm ci
    # Run
    - run: npm run lint
    - run: npm run reference -- --check

  test:
    strategy:
      matrix:
        # container: ["node:current", "node:lts"]
        container: ["node:current"]
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
    # Prepare
    - uses: actions/checkout@v2
    # NOTE: npm workspace support from npm 7, so need to update npm when using nodejs 14
    - run: |
        npm i -g npm
        npm ci
    - name: "Show version"
      run: |
        node --version
        npm --version
    # Run
    - run: npm run build
    - run: npm run test
