name: "CI"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Prepare
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: 'npm'
    - run: npm ci
    # Run
    - run: npm run lint
    - run: npm run format:check
    - run: npm run reference -- --check

  test:
    strategy:
      matrix:
        node-versions: ["20", "lts/*"]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    # Prepare
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-versions }}
        cache: 'npm'
    - run: npm ci
    - name: "Show version"
      run: |
        node --version
        npm --version
    # Run
    - run: npm run build
    - run: npm run test

  pack:
    runs-on: ubuntu-latest
    steps:
    # Prepare
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: 'npm'
    - run: npm ci
    # Run
    - run: npm run pack
